### ISSUE TITLE
Possibility of taking over maintenance/ownership?

### ISSUE THREAD

**Issue by gylaz** [stereobooster/jshintrb#19]
Hi @stereobooster,

It seems this project hasn't been updated or maintained in quite a while.

Is it possible for me, or my organization (I work for thoughtbot) to take over ownership of this? One of our projects uses your repo, and we have need in maintaining this gem.

What are your thoughts?

**Comment by jc00ke** [comment]
@stereobooster any thoughts on @gylaz's proposal?

**Comment by blainekasten** [comment]
+1 @gylaz

**Comment by grekko** [comment]
@gylaz Are you still interested to take over?
@stereobooster Would you mind letting @gylaz work on it?

**Comment by stereobooster** [comment]
I do not see sense to support this project. In 2017 it makes sense to use ESLint or Flow (to check JS files) or TypeScript (to check JS files, not talking about using TS instead of JS). So I consider this project as deprecated.
